### ISSUE TITLE
Sorting Filter does not get saved

### ISSUE THREAD

**Issue by NiGHTM4R3** [Dynious/RefinedRelocation#276]
After a certain point in the list the sorting just resets, this happens everytime and with every mod near the bottom of the list with many mods installed (especially with modpacks)
Mods near the top of the list work just fine.
I know you are aware of the issue but as a temporary fix let me suggest something since you already added some wildcard functionality (* as wildcard, ! as oredictionary): 
Let us use the NEI system of adding mod names for example if a mod does not sort by ticking the checkbox then entering @"Modname" would still sort it to the corresponding chest.

**Comment by Dynious** [comment]
What version of Refined Relocation are you running?

**Comment by NiGHTM4R3** [comment]
I was running 1.0.7f as I was unaware that you updated it 27h ago, now everything works as intended, I still would love a filter where I can actually enter the mod name though, so you could just take this as a suggestion instead of an issue.

**Comment by Dynious** [comment]
Does it work now? I haven't changed anything related to the filter list. It's really weird, this issue pops up sometimes and I can't figure out why :(

**Comment by Dynious** [comment]
Seen reports of this in newest version, really needs to be fixed!

**Comment by blay09** [comment]
The issue might just be caused by the loading order of the classes and RR keeping a reference to an older creative tab array. 

On the server, we only grab the creativeTabArray once, as soon as the FilterStandard class is loaded. However, the reference is then stuck on that array, which is no good because any CreativeTabs instance that is constructed now will not be reflected in the creative tab array that RR is using for the filtering (CreativeTabs constructor will create a new array when the new tab exceeds the current array size but our tabs array in FilterStandard will still point to the old one).

Due to the size checks that are being done, all creative tabs that were added after the FilterStandard class was loaded will just be ignored silently (both in saving to NBT and by the  (otherwise, this would have causes ArrayIndexOutOfRange exceptions).

The reason it doesn't even send the filter update to the server is a second issue which is related however; in fact, it's the same issue that's just affecting things differently: again we allocate a creativeTabs array only to the size of "tabs", which has a potentially old length since FilterStandard might not have been loaded last. Therefore, getSize() might return a smaller size than there actually is (since syncTabs doesn't update that array length either) and therefore the GUI's getSize() check will also silently fail, not sending the update to the server.

That's the long explanation, now to work on the short fix...
