### ISSUE TITLE
Suggestion: Making the custom filter prioritize above general filters

### ISSUE THREAD

**Issue by pckuijper** [Dynious/RefinedRelocation#285]
While using your mod if run into the problem that I want certain chests organized in a certain way.
Playing with the priority modifier gives a great deal of flexibility already but my issue comes in with the custom filters.
When i set a custom filter this will 90% of the time take priority over a group I might have selected.
Therefore I suggest having the custom filter take main priority and if an item fits into a custom filter then use that storage else use the selected pack.

**Comment by Dynious** [comment]
I would prefer this to work in this same way too, but the system currently in place does not allow sorting like this. Basically, the 'grid' doesn't know how an inventory decides an itemstack can enter, so it can't differentiate between list and custom filter sorting. I can't change this as it will break mods using the system currently in place.

**Comment by Someweb** [comment]
That's really quite a shame. That I think is the main problem that's keeping me back from considering this a full replacement for ME for me. I don't mind crafting things myself and I could even live without a single place to view all my items (although I'd love it if you put that in ;) ) but having tons and tons of items without being able to properly get everything flowing the way I want. I really hope in the future this can and will be changed.

**Comment by blay09** [comment]
I can see a solution for this, especially now that we have the new, modular filtering system, but I'm not sure if this is something we actually want - it increases complexity in a pretty non-obvious way (how would users know that custom filters are always prioritized higher?).

Is this just a convenience thing (as in I don't want to set all my user filters to higher priority, the mod should assume I want that) or is there an actual problem making things not work that I don't see yet?

**Comment by Someweb** [comment]
The problem that I'm having specifically is that for example I have a chest filled with Thaumcraft items and a separate chest with mob drops. In this case I would like the zombie brains (from TC) go into the mob drop chest since they're usually "junk". In this case I'd have to put the zombie brains as a custom filter in the mob drop chest. This will work fine if they both get the same priority. But as soon as one or the other gets a higher priority the system gets confused as to where to put this. This happens quite quickly when having a large amount of chests. This requires a lot of priority fiddling and quickly makes it quite messy with all the different priorities. Especially when having a lot of custom filters to put things exactly where you would want them to go. Hopefully this makes things more clear.

I'd make a screenshot but I have since moved over to boring old AE since it was just easier. I'd still love to go to a chest based system as I think that's quite fun and more challenging then having a tiny 5x5 structure to hold a million of what ever you throw in there.

**Comment by blay09** [comment]
I can see what you mean. I'll have a closer look at that solution I had of doing this to see if I can do it without breaking everything.

**Comment by blay09** [comment]
I got the issue number mixed up, but I proof-of-concepted my solution here:

https://github.com/Dynious/RefinedRelocation/commit/d1bfa514419cc12a2a4c3c10a8e9e7a879583569

Any thoughts on this, @Dynious (relevant classes are SortingGrid and FilterResult)?

**Comment by Dynious** [comment]
Hmmm, I'm not sure. It would give users more options and allow for better setups, but I don't want to overwhelm users with options. I think that if we do this we would need to properly redo the system in 1.8. Maybe we can then hide some settings under an advanced toggle. I have added some things like this to the system while trying to keep the API working for older mods and is been giving a lot of problems (see the ME system + Barrel issues).

**Comment by blay09** [comment]
The complexity shouldn't be that big of a problem. Userfilter only has a textbox right now, one "Always prioritize" button wouldn't hurt it.

But I do agree that it's not the most beautiful way of doing things and was going to suggest only switching over at 1.8 too, so we can have it be less-hacky (for performance sake, too).
But basically, this is how I see it done (be it 1.7.10 or 1.8, just without the hacky extra checks there).

**Comment by Dynious** [comment]
From #342

Sorting could be extended to be more powerful by adding an optional weighted value on whitelisted items/groups that would override the container's default weighted value.

Example of case use:
Chest 1 has a high weighted value, and has a broad filter of "Building Blocks" set, and contains cobblestone and gravel, etc.
Chest 2 has a normal weighted value, but you want a specific building block "Sand" in it, along with other items from other filters.
You would like these two cases to be true without altering the sorting weighted value of the rest of the chests contents.
