### ISSUE TITLE
Relocator Modules popping of after relogging (-> chunk un/loading?)

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#291]
as taken from [MCF](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293062-refined-relocation-1-0-8-solves-your?page=19#c373):

"I had an issue with a large grid of relocator pipes attached to the sides of block extenders. To be more explicit, I had a 3x3 array of auto-hammers and auto-sieves separated by 1 block gaps, each with a block extender located below. I was utilizing 3 connections per extender: 1 (down) for power, 1 for a stock module, and 1 for a blocked extraction module per extender.
Setting it up was no problem, it worked beautifully, until I logged off (single player) and started up again. Randomly (or at least to no pattern discernible by me) some of the modules popped off their relocator pipes and were resting on the ground when I loaded in. I tried multiple configurations... initially I thought it was if 2 modules were on the same pipe, but even after re-architecting so that all stock modules were NORTH, all blocked extraction modules were WEST, and the other 2 sides were blocked by covers, I still had some random modules pop off the pipes.

When I re-arranged things so that I did not use stock modules (only a single extraction module attached to DOWN, and power to the sides), I no longer had issues with modules popping off."

**Comment by Dynious** [comment]
Related to #273, which was thought to be fixed.

**Comment by Dynious** [comment]
I think I know what's happening. Kind of the same as the other issue, but a little more rare. 

1. World loads, relocator loads first, might not be able to connect to Block Extender because it's not initialized yet, but the fix of #273 will make sure module doesn't drop.
2. Nearby block loads (could be other block extender) and notifies neighbors of change.
3. Relocator will now check all sides (including the still not loaded Block Extender) and (because it's a block change notify) WILL drop modules.

**Comment by Dynious** [comment]
This way too complicated system is working fine now, should be fixed! http://i.imgur.com/2iANzbw.png
