### ISSUE TITLE
Crafting Upgrade does not use up clogged items for the crafting

### ISSUE THREAD

**Issue by JimmyTheBoat** [Dynious/RefinedRelocation#303]
Not sure if this affects all pipe modules, I've only seen it with crafting module on pipes. Anyways, it would be nice if there was a config to disable the clogging of these modules.

**Comment by blay09** [comment]
From what I've tested they only clog up if the items have no other place to go, otherwise the items just bounce back. If you were to disable the clogging, then where would the items end up going?

I think the real issue here is that it seems to be not using up the clogged items for the crafting but attempts to send the raw materials to the target inventory instead.

**Comment by JimmyTheBoat** [comment]
Ah, I'll just put a XU rationing pipe on my cobble gen as a fix then.

**Comment by Nonsanity** [comment]
The way I expecting things to work, any item entering the network should return to the module that injected it if it can't find a valid destination. If it cannot reach that module because of a one-way module, it should stick inside that one-way module. If its original module is broken and removed, the item can pop out as an drop at the module's location, once it gets there. If the network itself is broken so that the item can no longer reach its injecting module, then, and only then, can it stick in some other module or maybe pop out as a drop—I'm not sure which will cause less problems. (Probably the drop.)

I don't know why ingredients get stuck in the crafting module, but it does cause my system to jam and stop working surprisingly often. I have to left-click the jammed modules to free the items. That gets everything working again. I had to make a blocking extractor module chest just to send those manually-released drops back into the network.
