### ISSUE TITLE
Possibly make blacklist/whitelist setting per-filter?

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#317]
"I want to whitelist ingots but blacklist ender io ingots"

**Comment by Delerium** [comment]
I was coming here for this exact thing, although my thought was to be able to do boolean custom filters.
Example:
Lets say I'm setting up a ex nihilo automation, and I want to pull in the different ore dusts, but don't want glowstone dust, I could type "+*Dust, -Glowstone Dust"

Your idea seems a little better though.  Perhaps even weighted by an alterable list order like this:
0 W *Dust
1 B Glowstone Dust

So in 0 it would add all items ending in dust to the filter, then in 1 it would remove Glowstone Dust from the filter, leaving you with all dusts but glowstone.

**Comment by Dynious** [comment]
I have considered this, but decided against it because:
1. requires a second blacklist pass on 'accepted' items, which means worse performance
2. the system back then didn't really allow it (required lots of work)

Now, we have rewritten the system, so point 2 may not be valid anymore. Point 1 is something I not that worried about anymore (performance impact seems to be too small to be a valid point).

So, we could probably do this now.
