### ISSUE TITLE
Requesting sorting trim for storage drawers.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Dynious/RefinedRelocation#322]
Sorting drawers have trim like Refined relocation has sorting connectors. When using the sorting drawers there is no purely decorative way to pass both the drawer information and refined relocation information over the same block.

**Comment by blay09** [comment]
If I understood this right, you're asking for the Storage Drawers trim block to act in the same way as Sorting Connectors and connected Sorting Inventories together?

From the looks of it, this is something that would have to be done on Storage Drawers' side. Tile entities need to implement the ISortingMember interface to be valid connectors inside a sorting grid.

Since Storage Drawers already adds compatibility for Refined Relocation, they might add this to their trims if you ask them nicely, since there's no real overhead involved in supporting this.

**Comment by blay09** [comment]
I've submitted a pull request for this at the Storage Drawers repo.

**Comment by blay09** [comment]
The pull request was accepted and Storage Drawers will be getting Sorting Trims once it's released. :)

**Comment by NolanSyKinsley** [comment]
Yay, thank you!
