### ISSUE TITLE
Alchemical Sorting Chests dupe bug

### ISSUE THREAD

**Issue by Gideonseymour** [Dynious/RefinedRelocation#330]
Shift clicking an item (say cobblestone) into an Alchemical sorting chest chain, where another chest is set to grab the cobble, the cobble will be moved into that chest, while still remaining in your inventory,

**Comment by blay09** [comment]
Can confirm.

@Dynious 

from ContainerEE:
```java
slot.putStack(ItemHelper.cloneItemStack(itemStack, Math.min(itemStack.stackSize, slot.getSlotStackLimit())));
slot.onSlotChanged();
if(slot.getStack() != null) {
    itemStack.stackSize -= slot.getStack().stackSize;
    slotFound = true;
}
```

The null check fails on the server because RR moves the item to another inventory when putStack is called. I'm pretty sure there's nothing we can do about this other than begging Pahimar to change it, so linking #294 with passion.

Workaround to disable alchemical sorting chests in 1.7.10 without people losing their chests:
Have them just act like regular chests in the new version, i.e. remove all the special functionality for them and disable the crafting recipe.

**Comment by Dynious** [comment]
Well, shit.

**Comment by blay09** [comment]
Can I take that as a "yes, let's disable Sorting Alchemical Chests and remove them in 1.8"?

**Comment by Dynious** [comment]
There's no good solution to this. I'd say yes.

**Comment by blay09** [comment]
Sorting Alchemical Chests have been removed in a backwards-compatible manner and will disappear completely within the next Minecraft version update Refined Relocation is ported to.

* Sorting Alchemical Chests will remain in players' worlds with all their content but no longer provide their sorting functionality. 
* All ways to obtain a Sorting Alchemical Chest have been disabled and putting a Sorting Alchemical Chest into a crafting table will revert it back to a normal one. 
* A tooltip has been added to Sorting Alchemical Chests and the name has been adjusted to hint at their removal.
