### ISSUE TITLE
Null pointer exception while rendering toolbox

### ISSUE THREAD

**Issue by Baughn** [Dynious/RefinedRelocation#332]
This happened just after I asked it to grab all my (many, many) wrenches, so I'm not sure exactly which one of them is causing it, but here's the crash log:

http://sprunge.us/gFDQ

**Comment by Baughn** [comment]
From the crash log, it had grabbed my Certus Quartz Wrench and my RotaryCraft Screwdriver.

**Comment by blay09** [comment]
The problem seems to lie with whatever wrench it is that caused the crash as it seems to have a null icon. From a quick look I don't see RotaryCraft screwdrivers being supported by the toolbox, so they shouldn't get grabbed. Could you check if the ID 5841 is indeed the RotaryCraft screwdriver and not some other wrench?

I've tested the IC2, AE2, BC and COFH wrenches, and they all worked fine for me.

The one's I didn't test were the Carpenter's Chisel/Hammer, Factorization's ChargeMeter, Mekanism's Configurator and Network Reader, Project Red's Screwdriver, Quarry+ Tool and Aroma's wrench (those are all that are supported). Did you possibly have any of these?

**Comment by Baughn** [comment]
I checked, by using /give Baughn 5841 to get it back. It is indeed the screwdriver.

I also had a chisel and a a RedLogic screwdriver in my inventory, but they weren't absorbed.

**Comment by blay09** [comment]
Tested on my current dev-version of Refined Relocation and with RotaryCraft V6f and the toolbox did not consume the wrench, as expected. Either some other mod is adding support for it or Refined Relocation removed it in between the last released version and now (but I can't check that since Curse is down right now). 

I don't think there's much more I can do other than waiting for more reports on this to nail the issue down or hoping that it'll be all resolved with the upcoming new release of Refined Relocation.

**Comment by Baughn** [comment]
I'll do some more tests. Speaking of which, it would be great if the toolbox *did* work with the screwdriver.

**Comment by Baughn** [comment]
Well, I finally got around to confirming it; the game crashes if I shift-right-click even with just the toolbox and rotc screwdriver in my inventory. Which is odd, for quite a few reasons.

I'm running TPPI2 0.1.1 with a few modifications, but TPPI2 doesn't include rotc, and I'm not aware of any mods which might have added toolbox support to the screwdriver.

And the screwdriver does, of course, have an icon.

I guess I'll play around a bit with the code...
