### ISSUE TITLE
ME System with ME Sorting Interface and Sorting Barrel unsyncs inventory

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#356]
I have a full barrel with a void upgrade connected to an ME Sorting Interface and a simple Terminal-Energy-Cell ME system with nothing else.

Putting another item of the type the barrel holds into the ME Terminal will put a full stack of said item into my mouse cursor, which only exists on the client though.

This does not happen with the same setup using a normal barrel & storage bus.

**Comment by henx125** [comment]
I've encountered a similar issue using the ME sorting interface and sorting barrels. 

In my case if an item that is stored in a barrel enters the system through AE2, then the AE2 interface will not show that it has access to it, even though it was correctly stored in the appropriate barrel. 

However, if the player places the item into the barrel manually or the item enters the system through a sorting chest, then the AE interface updates correctly. I am assuming this means that sorting barrels never send a 'refresh' function to the system when storing a new item but other means of storage does. 

Also, as a work around, I have simply created 3 igneous extruders continuously dumping cobble into a sorting chest attached to the system; This forces the system to update and refresh at set intervals so that it functions effectively as it should.

**Comment by Nezraddin** [comment]
I have to add a "dupe-bug-report" to this issue.
In the modpack I play with it (refined relocation has the newest version, applied energistic the rv3-Beta-5 version) I tested around with this ME->Sorting barrel system.

It seems when you take the full amount of items out of the barrel using a ME-terminal it works fine (taking the items actually out). Same problem as aboth that when you put them back they not appear in the ME system anymore.
However, when I took less than the barrels current inventory out it duped the items. 
E.g. the barrel had 64 cobble inside, I took 32 out with right'clicking on cobble in the ME-terminal. The barrel still had 64 cobble inside 'plus' the 32 I just had taken out.

I tested it with several other items and - at least in this modpack - it was always duping the items.

(Modpack is Bevo's tech pack if that is important to know, in case it doesn't show this bevahior in other modpacks)
