### ISSUE TITLE
Wireless Block Extender not extracting everything

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#372]
"Also I have a furnace connected with a wireless block extender with a extraction module with no filter. Some items (food) goes out, others do not (stone)."

Taken from #369

**Comment by blay09** [comment]
@toticorrea I can't reproduce this issue. I got a Wireless Block Extender linked to a furnace, a relocator with extraction module on it, I/O side is configured to bottom. No filters set up and in Unfiltered Extraction Mode, going into a Vanilla Chest. It's pulling out all kinds of smelted things fine (ingots, food, stone).

**Comment by toticorrea** [comment]
It seems the problem it is not the wireless block. I found problems with items do not going out of the chests in other places too. I believe the problem is in the extraction modules. I could reset the one I mentioned first and then the items could get out from the furnace and goes where they suppose to. But I have a very complex set up with a lot of relocators and sorting modules around and I reset a couple of them with no luck like the first one with the furnace, So I do not know exactly where is the issue, but I am 90% sure is about the sorting of the modules.

**Comment by toticorrea** [comment]
Also, if I have one chest connected with relocators tubes comming from different places, and this chest is sorting connected with like others 20 chets. If I do not put any filter on it, the items wont pass through  it to the correspondet chest? Is this a new configuration with the new update?

**Comment by toticorrea** [comment]
sorry. I put extraction module before in the second line. I ment sorting module

**Comment by toticorrea** [comment]
I have just tested something. This chest is connected with a relocator with an extraction module, and then a sorting module to divide items, with blacklist on food. This system was perfect before the update. Now nothing goes out from the chest. I was trying everythng, reseting the filter module, taking it out, etc. Suddenly I took it out and out it again, and walah, all items started to travell. But as soon as I re calibrate the filter the way I want it, again nothing is going out from the chest. And I can not repeat the same step.

**Comment by toticorrea** [comment]
Hi Blay! Me again. Just instaled the new RR -1.1.16- and no good news, Still having problems with the Wireless Block Extender. Still does not want to extract what it is being told to. After a couple of minutes, game crashed. I was trying to put different set ups in the WBE with no luck and pum. But as I comment months ago, I think the problem is in the extrqaction modules. This is the log:

[crash-2016-02-04_16.21.21-server.txt](https://github.com/Dynious/RefinedRelocation/files/118086/crash-2016-02-04_16.21.21-server.txt)
