### ISSUE TITLE
UI freeze when removing a comma at the end of a line

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#373]
"Also just got a hung UI when I was trying to remove a comma at the end of a line (which might have been accepting everything? can't confirm)"

Taken from #369

**Comment by blay09** [comment]
@TruePikachu are you able to reproduce this issue? Things seem to be working fine for me.

**Comment by TruePikachu** [comment]
Haven't gotten it again, not sure if it was because of the comma specifically. Might have been a one-off bug, and I've migrated my equipment away from RR since (I use RR before I get a ME net built). I'll see if I can get my cheats test world to get it, though. Also I'll see if I can find the crash log.
