### ISSUE TITLE
Crash when placing Witchery items into sorting system

### ISSUE THREAD

**Issue by Alaberti** [Dynious/RefinedRelocation#375]
The below issue occurs when a witchery item is placed into a sorting system with a filter that tries to move it. I was using a trio of sorting chests adjacent to each other, the leftmost chest having a custom filter (*tongue*) and I placed a tongue of dog into the rightmost chest. 

http://pastebin.com/7yy18Lms

**Comment by blay09** [comment]
This looks like it could be caused by you having a mod installed on the client that adds a creative tab that doesn't exist on the server. I added a safety check so it doesn't crash next time, but you may end up getting things sorted weirdly if the creative tabs are out of sync with the server. This is an issue with how Refined Relocation handles the Creative Tab Filter internally and would require too much effort to justify fixing it for 1.7.10, since I've started work on the 1.8.9 version. I'll certainly consider this situation when implementing it on 1.8.9 though.
